### ISSUE TITLE
[Data Retrieval] mexico_earthquake on Crisis MMD

### ISSUE THREAD

**Issue by IanMagnusson** [MangeFre/IITUDND#11]
run data retrieval script with:

TWEET_ID_FILE =  mexico_earthquake_ids.txt (located in CrisisMMD_raw_tweets_ids.tar.gz)

USER_ID_FILE = mexico_earthquake_final_data.json (located in CrisisMMD_v1.0.tar.gz subfolder json)

OUTFILE = "mexico_earthquake_extras.json"

ERROR_FILE = "mexico_earthquake_extras_spill.json"

**Comment by MangeFre** [comment]
Running this tonight

**Comment by MangeFre** [comment]
This is completed.

**Comment by MangeFre** [comment]
EXTRA: There was one error - the very first user could not be parsed due to some weird html tags <> in the text. Json does not approve. Every other user worked perfectly fine.
