### ISSUE TITLE
[Data Retrieval] redo maria on Crisis MMD

### ISSUE THREAD

**Issue by IanMagnusson** [MangeFre/IITUDND#12]
run data retrieval script with:

TWEET_ID_FILE =  maria_tweet_ids.txt (located in CrisisMMD_raw_tweets_ids.tar.gz)

USER_ID_FILE = hurricane_maria_final_data.json (located in CrisisMMD_v1.0.tar.gz subfolder json)

OUTFILE = "maria_extras.json"

ERROR_FILE = "maria_extras_spill.json"

**Comment by MangeFre** [comment]
Running this as well.

**Comment by MangeFre** [comment]
Finished download, needs to upload to drive

**Comment by MangeFre** [comment]
Uploaded the extras file to Drive. No error file was created (no errors, yay)
