### ISSUE TITLE
Write script to get images (think about image resolution) 

### ISSUE THREAD

**Issue by chloelarkin** [MangeFre/IITUDND#3]

**Comment by MangeFre** [comment]
Filename idea: USER_ID + Tweet_Id + index.
Example: 12334_12421_0 (user + tweet + index. Next one would be 12334_12421_1)

**Comment by MangeFre** [comment]
A merge request has been made for this. Should be a good enough stary for us to attempt some downloading.

NOTE: Image sizes has not been kept in mind - the script just gets the images as they are.
